### ISSUE TITLE
Issu with the self-hosting site when it's more than 768px width.

### ISSUE THREAD

**Issue by Multigriffes** [elevedirect/app#1]
The side bare don't show up.
The different homeworks can't be seen.
Everything turn crazy 😮 
![image](https://user-images.githubusercontent.com/90653170/207182586-ce751491-ce56-4711-abf4-8e868b6a579a.png)

**Comment by camarm-dev** [comment]
Hey thanks for all your issues...
I'm not currently working on a PC version of the website but if you want I can work on a large screen version...

**Comment by camarm-dev** [comment]
bb1bfc52f96f2f8f4da199db2bad1dc03c79e4df
