### ISSUE TITLE
establishment don't accurate

### ISSUE THREAD

**Issue by Multigriffes** [elevedirect/app#2]
Showing EcoleDirecte
![image](https://user-images.githubusercontent.com/90653170/207182933-e5365918-d0c9-47f7-a776-480543925f6a.png)

**Comment by camarm-dev** [comment]
Thanks ! I think it comes from Ecoledirect api (which is very bad) because the configurations options that are set by the établissement seems to be very different from one school to anouther... I will look at this soon.

**Comment by Multigriffes** [comment]
Ok
