### ISSUE TITLE
Self-hosting error : folder missing

### ISSUE THREAD

**Issue by Multigriffes** [elevedirect/app#3]
When we start for the first time the web server an error show up telling it's missing the file test.png on cache folder.
I fix it by just creating a folder named cache.
![image](https://user-images.githubusercontent.com/90653170/207186465-2accc085-74d2-4683-874a-436559f5a549.png)

**Comment by camarm-dev** [comment]
Thank you. I think I will add a step on README installation guide to fix this issue.
