### ISSUE TITLE
Pourquoi les issues en anglais ?

### ISSUE THREAD

**Issue by Chromosore** [elevedirect/app#7]
Puisque le public est exclusivement français il n'y a pas trop d'intérêt mais surtout quand j'ai vu ~~l'issue~~ le ticket #2 j'ai été surpris puisque on ne dit pas establishment mais simplement school et surtout pas _don't accurate_ mais **isn't** accurate !

Ceci dit, faites comme vous voulez. Merci beaucoup pour avoir fait élève direct aussi !

**Comment by camarm-dev** [comment]
**Hey**, effectivement les tickets en anglais ne sont pas vraiment appropriés, dans le cadre où Ecoledirect est un service exclusivement français. Ceci dit utiliser l'anglais dans un projet communautaire a pour but de faire place à une communauté plus large et universelle, il est donc principalement écrit pour être compris, avec parfois des fautes... Ce projet reste utilisé par très peu de personnes et est développé par des étudiants.
Les tickets futurs seront écrits en français, même si ils risquent de se rarifier avec les vacances scolaires et un changement d'ENT de ma part.
Merci d'utiliser elevedirect et à bientôt !
